print("hello, what is your name?")
name = input()
print('hello,', name)
print('how are you?')
ok = input()
print('why are you so', ok)
because = input()
print('ok, will we play today?')
answer = input()
print('why', answer)
wmw = input()
print('ok, lets work')
print('look, what i can do')
print('choose a number: ')
num1 =  input()
print('choose a number: ')
num2 = input()

SUM = int(num1) + int(num2)

print(SUM)
print('can your calculator do the same?')
v = input()
print('because im better, than calculator!')
whate = input()
print('i dont know, because i must watch youtube and learn more about me.')
